name = ('Acer')
color = ('black')
memory = ('1-t')
ddr = ('SSD')
memory_ddr = ('256')
print('Название ноутбука:',name)
print('Цвет:', color)
print('Память:', memory)
print('Тип жесткого диска:', ddr)
print('Память диска:', memory_ddr)
